[project]
name = "chandra_pdf2md_client"
version = "0.1.0"
description = "chandra client to communicate with chandra vllm server."
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "filetype>=1.2.0",
    "markdownify>=1.2.2",
    "openai>=1.106.1",
    "pillow>=11.3.0",
    "pypdfium2>=5.0.0",
    "six>=1.17.0",
]
